### ISSUE TITLE
Ordering by Up/Down votes is not working

### ISSUE THREAD

**Issue by DonCarnohan** [th3conc3pt3ur/minionMaster#1]
When viewing the deck list it would be useful to be able to sort by up/down votes. It looks like it's trying based on the query parameters but the list doesn't re-arrange.

Just go to the Deck list and click on the thumb up / down in the table header to replicate.

**Comment by th3conc3pt3ur** [comment]
Yes replicate here too. On the fix ;)

**Comment by th3conc3pt3ur** [comment]
Should be good now 👍 
It's ok for you ?
